### ISSUE TITLE
$ is not defined 

### ISSUE THREAD

**Issue by MarcoDias7** [scottharwell/GoogleCharts#21]
Hi,

I had this error in the console when I tried to display the chart, any idea why ?

I think I already included JQuery in my view, so I don't know what's not working.

Thanks a lot !

**Comment by lolrofl** [comment]
Hi Marco,

How did you include JQuery in your view?

Love,
JB

**Comment by scottharwell** [comment]
Google Charts isn't dependent on jQuery.  This is likely another JS issue on your site that is causing other JS to fail.
